[package]
name = "langtonsant"
version = "0.1.0"
authors = ["Alexander Yankov <yankov.alex@gmail.com>"]
edition = "2018"

[dependencies]
termion = "1.5.2"
clap = "2.33.0"
palette = "0.4.1"
nalgebra = "0.18.0"
