[package]
name = "langtonsant"
version = "0.2.0"
authors = ["Alexander Yankov <yankov.alex@gmail.com>"]
edition = "2018"

[dependencies]
termion = "4.0.5"
clap = { version = "4.5.35", features = ["derive"] }
palette = "0.7.6"
nalgebra = "0.33.2"
